# Need trusty distro to work with java <9
dist: trusty
language: java
env:
  - MAVEN_VERSION=3.3.9
  - MAVEN_VERSION=3.5.4
  - MAVEN_VERSION=3.6.3
jdk:
  - openjdk7
  - openjdk8
  - openjdk11
  - openjdk-ea
install:
  # Specify version of io.takari:maven that supports Java 7
  - "mvn -q -N io.takari:maven:0.5.0:wrapper -Dmaven=${MAVEN_VERSION} -Dhttps.protocols=TLSv1.2"
script:
  - 'export MAVEN_OPTS="-Xms64m -Xmx256m -Djava.awt.headless=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"'
  - './mvnw --show-version --errors --batch-mode clean verify'
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - mfriedenhagen@apache.org
        - khmarbaise@apache.org
